export const quotes = [
  "You are the love of my life, my forever and always 💖",
  "Every moment with you is a dream come true 🌹",
  "My heart belongs to you, always and forever 💕",
  "You're the reason my heart beats 💓",
  "I love you more than words can say 🥰",
  "You’re my sunshine on the cloudy days ☀️",
  "With you, I feel complete ❤️",
  "My world is so much better with you in it 🌍💖",
  "You're the best part of my day, every day 🌸",
  "You're my favorite hello and hardest goodbye 😘",
  "I can’t imagine life without you in it 💑",
  "You are my everything, my reason to smile 😊",
  "I’m so lucky to have you by my side 🍀",
  "You make my heart skip a beat 💓",
  "I adore everything about you 💕",
  "You're the love I've always dreamed of 💭💖",
  "No one makes me feel like you do 😘",
  "You’re my person, now and forever 🌹",
  "Being with you is all I ever wanted 💑",
  "I never want to let you go, you’re my heart 💘",
  "You make every day brighter 🌟",
  "My love for you grows with every passing day 🌱💖",
  "I’m thankful for every moment we share 🙏💞",
  "I’ll love you till the stars fade away 🌠",
  "You are my dream come true 😍",
  "I’m yours, forever and always 💖",
  "You make my world beautiful 💫",
  "You are my forever, my always 💖",
  "You're the rhythm of my heart 🎶❤️",
  "Life with you is a beautiful adventure 🚀",
  "You complete me, in every way 💕",
  "My love for you is endless and unconditional 💞",
  "With you, every day is Valentine’s Day 💝",
  "You make me the happiest person on earth 🌍",
  "You're my home, wherever we are 🏡",
  "You’re my one and only, always 💘",
  "Loving you is the easiest thing I’ve ever done 💕",
  "I love the way you make me feel special 🌸",
  "You’re the sparkle in my eyes ✨",
  "I’ll love you forever, no matter what ❤️",
  "You’re my favorite place to be 💖",
  "Every second with you feels like magic ✨",
  "You’re my soulmate, my heart’s desire 💖",
  "Loving you is my favorite thing to do 💘",
  "You're my world, my heart, my everything 🌍❤️",
  "I can’t get enough of your love 💋",
  "I would choose you, over and over again 💖",
  "My heart is yours, forever and always 💘",
  "You're my greatest treasure 🏆💖",
  "I love you more than yesterday, but less than tomorrow 💞",
  "I’m so lucky to have found my forever with you 💑",
  "You’re the light of my life 🌟💖",
  "Every moment with you is a beautiful memory 📸💓",
  "You’re my forever and always, no matter what 💘",
  "I’m happier with you by my side 💖",
  "I could spend forever with you and never get bored ⏳❤️",
  "You’re the reason I believe in love 💖",
  "Your smile is my favorite thing in the world 😊",
  "You make my heart soar 🦅💖",
  "There’s no one I’d rather be with than you 💑",
  "Your love fills me with joy, every day 💖",
  "You are my greatest adventure, my love 💞",
  "I love how you make everything better 💖",
  "You're my heart's desire, now and forever 💘",
  "You make every day worth waking up to 🌞❤️",
  "You're my favorite chapter in this love story 📖💖",
  "I love you more than words can express 💖",
  "You’re the best decision I’ve ever made 🥰",
  "With you, life is a beautiful journey 🌺💖",
  "You are my dream come true 😍💖",
  "Loving you is the best part of my life 💑",
  "I’m so in love with you, every day 💘",
  "You're my safe place, my heart’s home 🏡❤️",
  "I feel so lucky to call you mine 🍀💖",
  "You are my forever love 💖",
  "You make my heart skip a beat every time 💓",
  "You complete my life in the best way 💖",
  "I’ll love you till the end of time ⏳💖",
  "You are the love story I’ll tell forever 📖💞",
  "I never knew what true love was until I met you 💖",
  "I cherish every moment with you 💖",
  "You are my happily ever after 💫",
  "I would do anything for you, my love 💘",
  "You're the best part of every day 🌅💖",
  "Every kiss from you is a promise of forever 💋💞",
  "You're my forever and always, no matter what 💘",
  "You make my life complete 💖",
  "You are the person I want to spend forever with ⏳💖",
  "I fall in love with you more each day 💕",
  "You're the love I never knew I needed 💖",
  "With you, I’ve found my true happiness 💖",
  "You are the most beautiful part of my life 💞",
  "You’re the one I want to grow old with 💑",
  "I can’t wait to spend forever with you 💖",
  "You’re the best gift life has given me 🎁💖",
  "You are my dream, my love, my everything 🌙💖",
  "You make me believe in fairytales 🏰💖",
  "I am so in love with you, forever 💘",
  "You are my heart’s only desire 💓",
  "Every day with you is a beautiful adventure 🌻💖",
  "You are my forever, my always, and my everything 💕",
  "Every time I look at you, I fall in love all over again 😍",
  "My heart is yours, today and always ❤️",
  "You are the best part of my life, my reason for smiling 😊",
  "I could spend forever in your arms 💞",
  "Your love is my favorite melody 🎶💖",
  "You’re the love of my life, my other half 💖",
  "You’re the reason I wake up with a smile every day 🌅💓",
  "You make my world brighter, one smile at a time 🌟",
  "I never knew what true happiness was until I found you 💘",
  "You are the reason my heart feels so full 💖",
  "I can't imagine a day without you in it 🥰",
  "You are my favorite thought before I fall asleep 😴💖",
  "Loving you is the most beautiful thing I've ever done 💞",
  "You're the best thing that's ever happened to me 🌹",
  "I love the way you love me 💘",
  "Every moment with you feels like a blessing 🙏❤️",
  "I would choose you over and over again, forever 💖",
  "You are the light in my life that makes everything shine 🌟",
  "Your love fills me with so much joy and warmth 💖",
  "I want to grow old with you by my side 💕",
  "You’re my reason for everything beautiful 💖",
  "I never knew what love was until I met you 💘",
  "You are my reason to believe in magic ✨💖",
  "Every time I hold your hand, I feel at home 🏡💖",
  "You make my heart feel like it’s dancing 💃💖",
  "I can’t stop thinking about you, you’re always on my mind 💭💞",
  "You’re the love story I’ve always dreamed of 📖💖",
  "You make every day a little bit better, just by being in it 💖",
  "I love you more than you’ll ever know 💘",
  "You’re the best part of my life, and I’m so grateful for you 💕",
  "You’re my heart’s favorite person, always 💖",
  "I love the way you look at me, it feels like magic ✨💘",
  "You’re the reason I believe in forever 💖",
  "I never want to spend a day without you 💞",
  "My heart beats for you, now and always 💓",
  "You're the one I want to share every moment with 💖",
  "You're the reason my heart feels so full ❤️",
  "You are my every dream come true 💖",
  "You make everything feel so much more special 💘",
  "I never thought I could love someone as much as I love you 💖",
  "My love for you will never fade 💞",
  "You are my favorite place to be 💖",
  "I feel so lucky to be loved by you 💕",
  "You make me feel like the luckiest person alive 💓",
  "You complete my world in every way 💖",
  "You are my always, my forever 🌹💘",
  "I’m so in love with you, it’s impossible to put into words 💖",
  "You are my sunshine on the darkest days ☀️💖",
  "You make my life feel so perfect 💞",
  "I love you with all my heart, now and forever 💓",
  "You are the best part of every day 💖",
  "I want to spend the rest of my life loving you 💘",
  "You are the one I’ve been waiting for 💖",
  "I love everything about you, from your smile to your heart 💘",
  "You are the love I never thought I’d find 💖",
  "I can't wait to make more beautiful memories with you 💞",
  "You make my heart feel like it’s soaring 💓",
  "Every time I kiss you, it feels like magic 💋✨",
  "I would do anything to make you happy 💖",
  "I love you more than I ever thought possible 💘",
  "You're my person, now and forever 💑",
  "I want to spend forever making you feel loved 💞",
  "Your love is everything I’ve ever wanted 💖",
  "I will always choose you, no matter what 💘",
  "You make my heart feel alive 💖",
  "I love being wrapped up in your love 💓",
  "With you by my side, I feel unstoppable 💪💖",
  "You’re my one and only, and I wouldn’t want it any other way 💘",
  "My heart is yours, forever and always 💓",
  "I feel complete when I’m with you 💖",
  "You are my forever love 💞",
  "You make me fall deeper in love with you every day 💘",
  "I want to spend every day with you, forever and always 💕",
  "You make every moment sweeter just by being there 💖",
  "I can’t imagine my life without you 💘",
  "You are the person I want to share my life with 💞",
  "Your love fills me with happiness I can’t explain 💖",
  "I want to make all your dreams come true 💘",
  "You make my heart race every time you smile 💓",
  "I will love you until the end of time, and even beyond 💖",
  "You’re my happiness, my love, my life 💖",
  "You are my forever, and I’m so lucky to have you 💘",
  "Every day with you feels like a gift 🎁💖",
  "I’m so thankful for your love, and I’ll cherish it always 💖",
  "You are the love of my life, and I’ll never let you go 💘",
  "I want to make every moment we share count 💖",
  "You’re my everything, today and always 💖",
  "You fill my life with love and joy 💞",
  "Loving you is the most beautiful journey 💖",
  "You are the light that guides me through the dark 💫💖",
  "I’m in awe of your love, it’s all I ever wanted 💖",
  "I want to spend forever holding your hand 💖",
  "You are the reason my world is so beautiful 💓",
  "I want to be with you through every chapter of life 📖💘",
  "You make my heart skip a beat, every time 💖",
  "I’m so grateful for your love, now and forever 💘",
  "You’re my dream come true, and I’ll cherish you always 💖",
  "I’ll always love you, no matter what 💞",
  "You are the one I’ve been waiting for, my true love 💘",
];
