export const quotes = [
  "You are the love of my life, my forever and always 💖",
  "Every moment with you is a dream come true 🌹",
  "My heart belongs to you, always and forever 💕",
  "You're the reason my heart beats 💓",
  "I love you more than words can say 🥰",
  "You’re my sunshine on the cloudy days ☀️",
  "With you, I feel complete ❤️",
  "My world is so much better with you in it 🌍💖",
  "You're the best part of my day, every day 🌸",
  "You're my favorite hello and hardest goodbye 😘",
  "I can’t imagine life without you in it 💑",
  "You are my everything, my reason to smile 😊",
  "I’m so lucky to have you by my side 🍀",
  "You make my heart skip a beat 💓",
  "I adore everything about you 💕",
  "You're the love I've always dreamed of 💭💖",
  "No one makes me feel like you do 😘",
  "You’re my person, now and forever 🌹",
  "Being with you is all I ever wanted 💑",
  "I never want to let you go, you’re my heart 💘",
  "You make every day brighter 🌟",
  "My love for you grows with every passing day 🌱💖",
  "I’m thankful for every moment we share 🙏💞",
  "I’ll love you till the stars fade away 🌠",
  "You are my dream come true 😍",
  "I’m yours, forever and always 💖",
  "You make my world beautiful 💫",
  "You are my forever, my always 💖",
  "You're the rhythm of my heart 🎶❤️",
  "Life with you is a beautiful adventure 🚀",
  "You complete me, in every way 💕",
  "My love for you is endless and unconditional 💞",
  "With you, every day is Valentine’s Day 💝",
  "You make me the happiest person on earth 🌍",
  "You're my home, wherever we are 🏡",
  "You’re my one and only, always 💘",
  "Loving you is the easiest thing I’ve ever done 💕",
  "I love the way you make me feel special 🌸",
  "You’re the sparkle in my eyes ✨",
  "I’ll love you forever, no matter what ❤️",
  "You’re my favorite place to be 💖",
  "Every second with you feels like magic ✨",
  "You’re my soulmate, my heart’s desire 💖",
  "Loving you is my favorite thing to do 💘",
  "You're my world, my heart, my everything 🌍❤️",
  "I can’t get enough of your love 💋",
  "I would choose you, over and over again 💖",
  "My heart is yours, forever and always 💘",
  "You're my greatest treasure 🏆💖",
  "I love you more than yesterday, but less than tomorrow 💞",
  "I’m so lucky to have found my forever with you 💑",
  "You’re the light of my life 🌟💖",
  "Every moment with you is a beautiful memory 📸💓",
  "You’re my forever and always, no matter what 💘",
  "I’m happier with you by my side 💖",
  "I could spend forever with you and never get bored ⏳❤️",
  "You’re the reason I believe in love 💖",
  "Your smile is my favorite thing in the world 😊",
  "You make my heart soar 🦅💖",
  "There’s no one I’d rather be with than you 💑",
  "Your love fills me with joy, every day 💖",
  "You are my greatest adventure, my love 💞",
  "I love how you make everything better 💖",
  "You're my heart's desire, now and forever 💘",
  "You make every day worth waking up to 🌞❤️",
  "You're my favorite chapter in this love story 📖💖",
  "I love you more than words can express 💖",
  "You’re the best decision I’ve ever made 🥰",
  "With you, life is a beautiful journey 🌺💖",
  "You are my dream come true 😍💖",
  "Loving you is the best part of my life 💑",
  "I’m so in love with you, every day 💘",
  "You're my safe place, my heart’s home 🏡❤️",
  "I feel so lucky to call you mine 🍀💖",
  "You are my forever love 💖",
  "You make my heart skip a beat every time 💓",
  "You complete my life in the best way 💖",
  "I’ll love you till the end of time ⏳💖",
  "You are the love story I’ll tell forever 📖💞",
  "I never knew what true love was until I met you 💖",
  "I cherish every moment with you 💖",
  "You are my happily ever after 💫",
  "I would do anything for you, my love 💘",
  "You're the best part of every day 🌅💖",
  "Every kiss from you is a promise of forever 💋💞",
  "You're my forever and always, no matter what 💘",
  "You make my life complete 💖",
  "You are the person I want to spend forever with ⏳💖",
  "I fall in love with you more each day 💕",
  "You're the love I never knew I needed 💖",
  "With you, I’ve found my true happiness 💖",
  "You are the most beautiful part of my life 💞",
  "You’re the one I want to grow old with 💑",
  "I can’t wait to spend forever with you 💖",
  "You’re the best gift life has given me 🎁💖",
  "You are my dream, my love, my everything 🌙💖",
  "You make me believe in fairytales 🏰💖",
  "I am so in love with you, forever 💘",
  "You are my heart’s only desire 💓",
  "Every day with you is a beautiful adventure 🌻💖",
  "You are my forever, my always, and my everything 💕",
  "Every time I look at you, I fall in love all over again 😍",
  "My heart is yours, today and always ❤️",
  "You are the best part of my life, my reason for smiling 😊",
  "I could spend forever in your arms 💞",
  "Your love is my favorite melody 🎶💖",
  "You’re the love of my life, my other half 💖",
  "You’re the reason I wake up with a smile every day 🌅💓",
  "You make my world brighter, one smile at a time 🌟",
  "I never knew what true happiness was until I found you 💘",
  "You are the reason my heart feels so full 💖",
  "I can't imagine a day without you in it 🥰",
  "You are my favorite thought before I fall asleep 😴💖",
  "Loving you is the most beautiful thing I've ever done 💞",
  "You're the best thing that's ever happened to me 🌹",
  "I love the way you love me 💘",
  "Every moment with you feels like a blessing 🙏❤️",
  "I would choose you over and over again, forever 💖",
  "You are the light in my life that makes everything shine 🌟",
  "Your love fills me with so much joy and warmth 💖",
  "I want to grow old with you by my side 💕",
  "You’re my reason for everything beautiful 💖",
  "I never knew what love was until I met you 💘",
  "You are my reason to believe in magic ✨💖",
  "Every time I hold your hand, I feel at home 🏡💖",
  "You make my heart feel like it’s dancing 💃💖",
  "I can’t stop thinking about you, you’re always on my mind 💭💞",
  "You’re the love story I’ve always dreamed of 📖💖",
  "You make every day a little bit better, just by being in it 💖",
  "I love you more than you’ll ever know 💘",
  "You’re the best part of my life, and I’m so grateful for you 💕",
  "You’re my heart’s favorite person, always 💖",
  "I love the way you look at me, it feels like magic ✨💘",
  "You’re the reason I believe in forever 💖",
  "I never want to spend a day without you 💞",
  "My heart beats for you, now and always 💓",
  "You're the one I want to share every moment with 💖",
  "You're the reason my heart feels so full ❤️",
  "You are my every dream come true 💖",
  "You make everything feel so much more special 💘",
  "I never thought I could love someone as much as I love you 💖",
  "My love for you will never fade 💞",
  "You are my favorite place to be 💖",
  "I feel so lucky to be loved by you 💕",
  "You make me feel like the luckiest person alive 💓",
  "You complete my world in every way 💖",
  "You are my always, my forever 🌹💘",
  "I’m so in love with you, it’s impossible to put into words 💖",
  "You are my sunshine on the darkest days ☀️💖",
  "You make my life feel so perfect 💞",
  "I love you with all my heart, now and forever 💓",
  "You are the best part of every day 💖",
  "I want to spend the rest of my life loving you 💘",
  "You are the one I’ve been waiting for 💖",
  "I love everything about you, from your smile to your heart 💘",
  "You are the love I never thought I’d find 💖",
  "I can't wait to make more beautiful memories with you 💞",
  "You make my heart feel like it’s soaring 💓",
  "Every time I kiss you, it feels like magic 💋✨",
  "I would do anything to make you happy 💖",
  "I love you more than I ever thought possible 💘",
  "You're my person, now and forever 💑",
  "I want to spend forever making you feel loved 💞",
  "Your love is everything I’ve ever wanted 💖",
  "I will always choose you, no matter what 💘",
  "You make my heart feel alive 💖",
  "I love being wrapped up in your love 💓",
  "With you by my side, I feel unstoppable 💪💖",
  "You’re my one and only, and I wouldn’t want it any other way 💘",
  "My heart is yours, forever and always 💓",
  "I feel complete when I’m with you 💖",
  "You are my forever love 💞",
  "You make me fall deeper in love with you every day 💘",
  "I want to spend every day with you, forever and always 💕",
  "You make every moment sweeter just by being there 💖",
  "I can’t imagine my life without you 💘",
  "You are the person I want to share my life with 💞",
  "Your love fills me with happiness I can’t explain 💖",
  "I want to make all your dreams come true 💘",
  "You make my heart race every time you smile 💓",
  "I will love you until the end of time, and even beyond 💖",
  "You’re my happiness, my love, my life 💖",
  "You are my forever, and I’m so lucky to have you 💘",
  "Every day with you feels like a gift 🎁💖",
  "I’m so thankful for your love, and I’ll cherish it always 💖",
  "You are the love of my life, and I’ll never let you go 💘",
  "I want to make every moment we share count 💖",
  "You’re my everything, today and always 💖",
  "You fill my life with love and joy 💞",
  "Loving you is the most beautiful journey 💖",
  "You are the light that guides me through the dark 💫💖",
  "I’m in awe of your love, it’s all I ever wanted 💖",
  "I want to spend forever holding your hand 💖",
  "You are the reason my world is so beautiful 💓",
  "I want to be with you through every chapter of life 📖💘",
  "You make my heart skip a beat, every time 💖",
  "I’m so grateful for your love, now and forever 💘",
  "You’re my dream come true, and I’ll cherish you always 💖",
  "I’ll always love you, no matter what 💞",
  "You are the one I’ve been waiting for, my true love 💘",
  "Tu es l’amour de ma vie 💕",
  "Mon cœur bat pour toi et toi seule 💓",
  "Avec toi, chaque jour est un rêve éveillé 😍",
  "Mon amour pour toi est infini ♾️💖",
  "Tu es ma plus belle histoire d’amour 📖❤️",
  "Ton sourire illumine ma vie ☀️💖",
  "À tes côtés, je me sens chez moi 🏡💘",
  "Je t’aimerai jusqu’à la fin des temps ⏳💕",
  "Dans ton regard, je vois mon avenir 💫👀",
  "Je suis à toi, maintenant et pour toujours 💍💖",
  "Tu es la plus belle chose qui me soit arrivée 💘",
  "J’ai besoin de toi comme l’air que je respire 💨❤️",
  "Tu es la lumière de ma vie 🌟💖",
  "Mon amour pour toi grandit chaque jour 🌱💘",
  "Je veux passer ma vie entière à t’aimer 💑💖",
  "Chaque instant avec toi est un cadeau 🎁💞",
  "Tu es mon âme sœur, mon évidence 💖✨",
  "Avec toi, j’ai trouvé mon bonheur 💕",
  "Mon cœur ne bat que pour toi 💓💘",
  "Tu es mon plus beau poème d’amour 📝💖",
  "Je t’aimerai dans cette vie et dans toutes les autres 💫💘",
  "Ton amour est ma plus grande richesse 💎💕",
  "J’ai trouvé mon paradis dans tes bras 🏝️💖",
  "Quand je suis avec toi, tout est parfait 💘",
  "Mon cœur est à toi pour l’éternité 💖💍",
  "Tu es mon plus doux secret 💌💞",
  "T’aimer est la plus belle chose qui me soit arrivée 💖",
  "Chaque moment passé sans toi me semble une éternité ⏳💘",
  "Tu es mon rayon de soleil dans l’ombre ☀️💖",
  "Ton amour est la plus belle mélodie 🎶💘",
  "Avec toi, je suis la meilleure version de moi-même 💕",
  "Tu es l’étoile qui brille dans ma nuit ✨💖",
  "Tu fais battre mon cœur plus fort à chaque instant 💓💘",
  "Tu es mon plus grand bonheur 💖",
  "Je suis fou/folle de toi 🤩💘",
  "Tu es le miracle que j’attendais dans ma vie 💫💕",
  "Rien ni personne ne pourra jamais nous séparer 💖",
  "Dans tes bras, je me sens invincible 💪💘",
  "Je veux te faire sourire chaque jour 💞😊",
  "Tu es mon rêve devenu réalité 🌠💘",
  "Je suis amoureux de toi plus que jamais 💖",
  "Chaque seconde avec toi est précieuse ⏳💕",
  "Mon amour pour toi est comme une étoile, éternel 💫💘",
  "Tu es ma définition du bonheur 💖",
  "Ton amour est ma plus belle aventure 🌍💘",
  "Tu es l’ange qui veille sur mon cœur 😇💖",
  "J’aime tout de toi, absolument tout 💕",
  "Ton amour est mon plus grand trésor 💎💘",
  "Je suis tellement fier(ère) de t’avoir dans ma vie 💖",
  "Mon cœur ne bat que pour toi, mon amour 💓💕",
  "Avec toi, chaque instant est magique ✨💘",
  "Tu es la raison pour laquelle je crois en l’amour 💖",
  "Je veux vieillir à tes côtés 👵👴💕",
  "Ton amour est mon refuge 🏡💘",
  "Je suis comblé(e) grâce à toi 💖",
  "Tu es mon monde, mon univers 🌍💘",
  "Tu es le souffle de ma vie 💨💖",
  "Mon cœur t’appartient, aujourd’hui et pour toujours 💓💘",
  "T’aimer est la plus belle chose que j’ai jamais faite 💖",
  "Tu es la plus belle étoile de mon ciel 🌟💘",
  "Tu es mon coup de foudre éternel ⚡💖",
  "Mon âme t’appelle chaque jour 💕",
  "Avec toi, je veux écrire une belle histoire d’amour 📖💘",
  "Tu es la plus belle partie de ma vie 💖",
  "Je ne veux que toi et rien d’autre 💕",
  "T’aimer me rend heureux comme jamais 💘",
  "Tu es mon souhait exaucé 💫💖",
  "Je veux t’aimer encore et encore 💕",
  "Mon amour pour toi ne cessera jamais 💘",
  "Ton sourire est ma plus belle lumière ☀️💖",
  "Je t’aime plus que les mots ne peuvent l’exprimer 💕",
  "Chaque jour, je tombe encore plus amoureux de toi 💘",
  "Tu es mon plus beau trésor 💎💖",
  "Mon bonheur, c’est toi 💕",
  "Ton amour est un cadeau précieux 🎁💘",
  "Je t’aime d’un amour éternel 💫💕",
  "Mon cœur bat au rythme du tien 💓💘",
  "Tu es mon éternité 💖",
  "À travers les années, je t’aimerai toujours 💘",
  "Tu es ma plus belle étoile 🌟💖",
  "Mon amour pour toi est comme l’océan, sans fin 🌊💕",
  "Chaque instant avec toi est un instant de bonheur 💘",
  "Tu es mon plus bel amour ❤️",
  "Je veux être celui/celle qui rend tes jours plus beaux 💖",
  "Ton amour est mon plus beau refuge 💕",
  "Tu es ma plus belle aventure 💫💘",
  "Mon cœur est à toi et le restera toujours 💖",
  "Avec toi, chaque jour est une fête 🎉💕",
  "Je suis amoureux de toi comme au premier jour 💘",
  "Tu es la plus belle surprise de ma vie 🎁💖",
  "Avec toi, la vie est plus belle 💕",
  "Mon amour grandit chaque seconde à tes côtés ⏳💘",
  "Ton amour est la mélodie de mon cœur 🎶💖",
  "Je veux être celui/celle qui te rend heureux chaque jour 💕",
  "Tu es ma douce folie 🤪💘",
  "Mon rêve, c’est toi 🌠💖",
  "Chaque battement de mon cœur te dit « Je t’aime » 💓💕",
  "Tu es mon âme sœur, ma destinée 💫💘",
  "Mon seul souhait, c’est de t’aimer toute ma vie 💖",
  "Toi et moi, c’est pour toujours ❤️💑",
  "Tu es la femme de ma vie, mon amour éternel 💖",
  "Quand je suis avec toi, le temps s’arrête ⏳❤️",
  "Je t’aime plus que tout au monde 🌎💕",
  "Ton sourire illumine mes journées ☀️💘",
  "Tu es mon plus grand bonheur 💖",
  "Chaque seconde loin de toi est une torture ⏳💔",
  "Dans tes bras, je me sens invincible 💪💞",
  "Ton amour est mon plus grand trésor 💎❤️",
  "Je veux passer ma vie à te rendre heureuse 💕",
  "Tu es la plus belle étoile de mon ciel 🌟💖",
  "Mon cœur bat uniquement pour toi 💓💘",
  "Tu es mon rêve devenu réalité 🌠💕",
  "Je suis fou de toi 🤩💖",
  "Avec toi, chaque jour est un cadeau 🎁💘",
  "Mon seul souhait est de t’aimer pour toujours 💞",
  "Tu es la plus belle chose qui me soit arrivée 💖",
  "Je veux être l’homme qui te rend heureuse 💘",
  "Ton amour est mon refuge 🏡💕",
  "Je t’aime plus que les mots ne peuvent l’exprimer 💖",
  "Tu es mon évidence, mon amour éternel 💘",
  "Chaque battement de mon cœur murmure ton nom 💓💞",
  "Tu es mon plus beau poème d’amour 📖💖",
  "Je veux vieillir à tes côtés 👴💕",
  "Ton amour me donne des ailes 🕊️💘",
  "Avec toi, je me sens complet 💖",
  "Tu es mon trésor le plus précieux 💎💕",
  "Mon amour pour toi est inépuisable 💖",
  "Je veux écrire l’histoire de ma vie avec toi 📖❤️",
  "Tu es mon plus grand coup de foudre ⚡💘",
  "Chaque regard de toi me fait fondre 😍💞",
  "Je suis accro à ton amour 💖",
  "Ton amour est la plus belle des mélodies 🎶💕",
  "Avec toi, tout semble possible 💖",
  "Tu es la raison pour laquelle je me lève heureux chaque matin 🌅💘",
  "Je veux être l’homme de ta vie 💞",
  "Mon cœur est à toi et à toi seul 💖",
  "Tu es mon univers entier 🌍💘",
  "Je ne peux plus imaginer ma vie sans toi 💕",
  "À tes côtés, je trouve la paix 💖",
  "Tu es mon plus beau miracle 💫💘",
  "Rien ne me rend plus heureux que ton sourire 😊💞",
  "Mon cœur bat plus vite quand je suis près de toi 💓💖",
  "Je suis prêt à tout pour te voir heureuse 💘",
  "Tu es mon soleil après la pluie ☀️🌧️💖",
  "Je suis amoureux de toi chaque jour un peu plus 💕",
  "Ton amour est la plus belle chose que j’ai jamais connue 💖",
  "Je veux t’aimer pour l’éternité 💘",
  "Avec toi, chaque jour est une nouvelle aventure 💞",
  "Tu es la raison pour laquelle je crois en l’amour 💖",
  "Mon plus grand rêve, c’est toi 🌠💕",
  "Dans tes bras, je trouve mon bonheur 💘",
  "Je veux partager chaque instant de ma vie avec toi 💖",
  "Ton amour est mon plus beau cadeau 🎁💕",
  "Tu es la seule qui fait battre mon cœur 💓💘",
  "Je suis tellement chanceux de t’avoir 💖",
  "Tu es mon essentiel, mon tout 💕",
  "Ton amour est ma plus grande force 💪💘",
  "À tes côtés, je me sens invincible 💖",
  "Tu es la lumière qui éclaire ma vie 🌟💕",
  "Je veux passer mes jours et mes nuits avec toi 💘",
  "Mon amour pour toi est sans limite 💖",
  "Tu es l’amour que j’ai toujours attendu 💞",
  "Je suis à toi pour l’éternité 💘",
  "Tu es mon ange gardien 😇💕",
  "Mon amour pour toi est indestructible 💖",
  "Je veux être le premier et le dernier à te dire `je t’aime` 💘",
  "À tes côtés, la vie est un rêve éveillé ✨💕",
  "Je veux être ton bonheur, ton sourire, ton tout 💖",
  "Tu es la femme qui fait battre mon cœur 💘",
  "Je t’aimerai au-delà du temps et des étoiles 💫💕",
  "Tu es mon oxygène, ma raison d’exister 💖",
  "Je veux être l’homme qui te rend heureuse chaque jour 💘",
  "Ton amour est ma plus grande richesse 💎💕",
  "Avec toi, chaque moment est magique ✨💖",
  "Tu es mon amour infini ♾️💕",
  "Rien n’a de sens sans toi 💘",
  "Ton sourire est mon soleil quotidien ☀️💕",
  "Tu es mon destin, mon avenir 💖",
  "Chaque jour avec toi est une bénédiction 🙏💕",
  "Mon cœur appartient à toi seul 💓💘",
  "Avec toi, je veux construire une vie de bonheur 🏡💕",
  "Ton amour est mon plus bel abri 💖",
  "Tu es la seule que je veux aimer pour toujours 💘",
  "Mon bonheur, c’est être à tes côtés 💕",
  "Tu es mon étoile la plus brillante 🌟💖",
  "Mon cœur et mon âme sont à toi 💘",
  "Tu es mon essentiel, mon inspiration 💕",
  "Dans tes bras, je suis chez moi 🏡💖",
  "Ton amour me donne la force de tout affronter 💪💕",
  "Tu es la plus belle partie de ma vie 💘",
  "Tu es ma plus belle étoile dans la nuit 🌌💖",
  "Mon amour grandit chaque jour à tes côtés 💕",
  "Tu es ma seule et unique, mon éternité 💘",
  "Je ne veux que toi et rien d’autre 💖",
  "Ton amour est un feu qui brûle en moi 🔥💕",
  "Je suis l’homme le plus heureux grâce à toi 💘",
  "Mon cœur ne connaît qu’un seul nom : le tien 💖",
  "Je t’aime au-delà des mots et du temps 💫💕",
  "Tu es l’amour de ma vie, aujourd’hui et toujours 💘",
  "Toi et moi, c’est pour la vie 💞💑",
];
